<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<project>
 <meta>
  <name>Demo Brushless Controller Project</name>
  <author>U. Bruhin</author>
  <version>v1</version>
  <created>2013-04-13T12:43:52Z</created>
  <last_modified>2016-09-08T23:11:32Z</last_modified>
 </meta>
 <attributes/>
 <schematics>
  <schematic>main.xml</schematic>
 </schematics>
 <boards>
  <board>default.xml</board>
 </boards>
</project>
